# Generated by Django 4.1.5 on 2023-01-10 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateField(default=datetime.datetime(2023, 1, 10, 10, 15, 50, 821698))),
                ('deadline', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
