# Generated by Django 4.1.5 on 2023-01-10 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
